name: 'Build and test'

on:
  pull_request:
  push:
    branches:
      - 'master'
  workflow_dispatch:

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=true -Dorg.gradle.parallel=true -Dorg.gradle.welcome=never

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest

    # A possible workaround for <https://github.com/dorny/test-reporter/issues/168>.
    permissions:
      checks: write
      contents: write
      pull-requests: write
      statuses: write
      # Explicitly granted, necessary for the `publish` step.
      packages: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'Set up Java 17'
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17
          java-package: jdk+fx

      - name: 'Cache ~/.konan'
        id: cache-konan
        uses: actions/cache@v4
        with:
          path: |
            ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('**/*.gradle.kts', '**/gradle-wrapper.properties') }}-build-java17
          restore-keys: |
            ${{ runner.os }}-konan-${{ hashFiles('**/*.gradle.kts', '**/gradle-wrapper.properties') }}-
            ${{ runner.os }}-konan-

      - name: 'Build'
        id: build
        uses: gradle/gradle-build-action@v3.3.2
        with:
          gradle-version: wrapper
          arguments: |
            build

      - name: 'Upload gradle reports'
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: gradle-reports
          path: '**/build/reports/'
          retention-days: 1

      - name: 'ShadowJar'
        id: shadow-jar
        uses: gradle/gradle-build-action@v3.3.2
        with:
          gradle-version: wrapper
          arguments: |
            shadowJar

      - name: 'Upload shadowJar'
        uses: actions/upload-artifact@v4
        with:
          name: server-all.jar
          path: 'server/build/libs'
          retention-days: 90